---
packages:
  - jq
  - exa
  - mosh
  - ncdu
  - fzf
  - fd
  - node
  - ripgrep
  - ansible
  - ansible-lint
  - yamllint
  - keychain
  - nmap
  - rclone
  - bat
  - tree
  - htop
  - rsync
  - lf
