---
- hosts: all
  roles:
    - kewlfft.aur
  vars:
    src_dir: "~/.local/src"
    xdg_config_home: "~/.config"
    xdg_data_home: "~/.local/share"
  tasks:
    - import_tasks: roles/dev/tasks/main.yml
    - import_tasks: roles/ui/tasks/main.yml
