---
- hosts: all
  roles:
    - kewlfft.aur
  vars:
    src_dir: "{{ ansible_env.HOME }}/.local/src"
    xdg_config_home: "{{ ansible_env.HOME }}/.config"
    xdg_data_home: "{{ ansible_env.HOME }}/.local/share"
  tasks:
    - import_tasks: roles/dev/tasks/main.yml
    - import_tasks: roles/ui/tasks/main.yml
