---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: no
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: macos
provisioner:
  name: ansible
verifier:
  name: ansible
