---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-arch
    image: arch-ansible
    pre_build_image: true
    pull: no
  - name: instance-ubuntu
    image: ubuntu-eoan-ansible
    pre_build_image: true
    pull: no
lint: |
  set -e
  yamllint .
  # ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
