---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-ubuntu
    image: geerlingguy/docker-ubuntu2004-ansible:latest
lint: |
  set -e
  yamllint .
  # ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
