---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-arch
    image: archlinux:latest
    pre_build_image: true
  - name: instance-ubuntu
    image: ubuntu-eoan-ansible
    pre_build_image: true
    pull: no
provisioner:
  name: ansible
verifier:
  name: ansible
