---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu-eoan-ansible
    pre_build_image: true
    pull: no
provisioner:
  name: ansible
verifier:
  name: ansible
