---
- name: Check for base-devel packages
  become: yes
  pacman:
    name: base-devel
    state: present

- name: Check for git package
  become: yes
  pacman:
    name: git
    state: present

- name: Check if yay is there
  stat:
    path: /usr/bin/yay
  register: yaystat

- name: Clone Yay repository
  when: yaystat.stat.exists == False
  git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: "{{ src_dir }}/yay"
    version: "master"

- name: "Create aur_builder user (on Arch)"
  become: yes
  user:
    name: aur_builder
    group: wheel

- name: "Add aur_builder user to suoders"
  become: yes
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: ALL'
    create: yes
    validate: 'visudo -cf %s'

    # - name: Install Yay
    #   become: yes
    #   become_user: aur_builder
    #   when: yaystat.stat.exists == False
    #   shell: >-
    #     echo "y" | makepkg -si
    #   args:
    #     chdir: "{{ src_dir }}/yay"

- name: Install Yay
  become: yes
  become_user: aur_builder
  when: yaystat.stat.exists == False
  aur:
    name: yay
    use: makepkg

- name: Colored output
  become: yes
  lineinfile:
    dest: /etc/pacman.conf
    state: present
    regexp: "^(.*)Color"
    line: "Color"
