---
- name: Load OS Specific vars
  include_vars: "{{ lookup('first_found', possible_files) }}"
  vars:
    possible_files:
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - ../vars/default.yml

- import_tasks: roles/common/tasks/dotfiles.yml
- import_tasks: neovim.yml
- import_tasks: zsh.yml
- import_tasks: tmux.yml
