---
- name: Ensure $XDG_CONFIG_HOME/tmux/plugins
  file:
    path: "{{ xdg_config_home }}/tmux/plugins"
    state: directory
- name: Ensure tmux is there
  become: yes
  package:
    name: tmux
    state: present
- name: Clone tmux config
  git:
    repo: 'https://github.com/alxlu/tmux-config'
    dest: "{{ xdg_config_home }}/tmux"
- name: Clone tpm
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ xdg_config_home }}/tmux/plugins/tpm"
