---
- name: Ensure tmux is there
  become: "{{ 'no' if ansible_os_family == 'Darwin' else 'yes' }}"
  package:
    name: tmux
    state: present

- name: Clone tmux config
  git:
    repo: 'https://github.com/alxlu/tmux-config'
    dest: "{{ xdg_config_home }}/tmux"

- name: Set push url to SSH
  git_config:
    name: "url.git@github.com:.pushInsteadOf"
    scope: local
    value: "https://github.com/"
    repo: "{{ xdg_config_home }}/tmux"

- name: Get dwm.tmux
  unarchive:
    remote_src: yes
    src: "https://github.com/alxlu/dwm.tmux/releases/download/0.1.1/dwm.tmux.tar.gz"
    dest: "{{ ansible_tmp }}"
    mode: '755'

- name: Install dwm.tmux
  make:
    chdir: "{{ ansible_tmp }}/dwm.tmux"
    target: install
