---
- name: Ensure $XDG_CONFIG_HOME/zsh
  file:
    path: "{{ xdg_config_home }}/zsh"
    state: directory

- name: Ensure zsh is there
  when: not ansible_os_family == "Darwin"
  become: yes
  package:
    name: zsh
    state: present

- name: Clone zsh config
  git:
    repo: 'https://github.com/alxlu/zsh-config.git'
    dest: "{{ xdg_config_home }}/zsh"
    update: yes
    force: yes

- name: Set push url to SSH
  git_config:
    name: "url.git@github.com:.pushInsteadOf"
    scope: local
    value: "https://github.com/"
    repo: "{{ xdg_config_home }}/zsh"

- name: Ensure ~/.zshenv is a link
  command: "ls -F ~/.zshenv"
  register: existing_zshenv_info
  failed_when: false
  check_mode: false
  changed_when: false

- name: Remove ~/.zshenv if it needs to be linked
  file:
    path: ~/.zshenv
    state: absent
  when: "'@' not in existing_zshenv_info.stdout"

- name: Symlink .zshenv
  file:
    src: "{{ xdg_config_home }}/zsh/.zshenv"
    dest: "~/.zshenv"
    state: link
  become: false

- name: Install zsh plugins
  command:
    cmd: 'zsh -i -c exit'
    creates: "~/.zinit"

- name: set zsh as default shell
  when: not ansible_os_family == "Darwin"
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
